cloud:
  aws:
    credentials:
      access-key: "cU6Na6YR+ufrppTDNgc1OU9KyNUIWsX8C9d1iil6"
      secret-key: "cU6Na6YR+ufrppTDNgc1OU9KyNUIWsX8C9d1iil6 "
    region:
      static: us-east-2
    stack:
      auto: false
